### PR TITLE
replace deprecated `Threading.isAlive()` method call

### PR DESCRIPTION
**Pull request by theStack**
The method has been deprecated since Python 3.8 and removed in Python 3.9, leading to the following error if ran with the latter:

```
Traceback (most recent call last):
 File "./bitcoin-submittx", line 463, in start
   join_all(threads, timeout)
 File "./bitcoin-submittx", line 342, in join _all
   alive += t.isAlive()
AttributeError: 'NodeConn' object has no attribute 'isAlive'
```

Using `Threading.is_alive()` fixes this; it should work with any Python version >= 3.5 as it's been there since, with the same functionality as `.isAlive()`.

### CODE REVIEW

**Comment by achow101** [comment]
ACK

**Comment by laanwj** [comment]
Sorry for the late reply. Thanks, ACK.
